dist: focal
sudo: required
env:
  global:
    - DOCKER_REPO=kevin0205/metricbeat
before_install:
  #- curl -fsSL https://get.docker.com | sh
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
     $(lsb_release -cs) \
     stable"
  - sudo apt-get install docker-ce-cli=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) docker-ce=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) containerd.io=1.2.13-2
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker/cli-plugins
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
  - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
  - sudo service docker start
install:
  #- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
  - docker buildx create --use --name xbuilder
  - docker buildx inspect xbuilder --bootstrap
script: bash ci.sh
