language: bash
services:
  - docker
dist: focal
sudo: required
env:
  global:
    - DOCKER_REPO=kevin0205/metricbeat
before_install:
  - curl -fsSL https://get.docker.com | sh
  - sudo systemctl restart docker
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  #- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  #- mkdir -p $HOME/.docker/cli-plugins
  #- wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
  #- chmod 0750 $HOME/.docker/cli-plugins/docker-buildx
  - docker version
  - docker buildx version
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - ls -al /proc/sys/fs/binfmt_misc/
  - docker buildx create --use --name xbuilder
  - docker buildx inspect xbuilder --bootstrap
  - docker buildx ls
#script: 
  #- travis_wait 50 sh -c 'bash ci.sh'
