language: bash
services: docker
#dist: focal
dist: xenial
sudo: required
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - DOCKER_REPO=kevin0205/metricbeat
    - TARGET_ARCH=linux/amd64,linux/arm64
    - TARGET_VERSION=7.6.2
    #- TARGET_VERSION=7.7.1
    #- TARGET_VERSION=7.5.2
before_install:
  # Install Docker
  - curl -fsSL https://get.docker.com | sh
  - sudo systemctl restart docker
  # Install Docker Buildx
  - mkdir -p $HOME/.docker/cli-plugins
  - wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
  - chmod 0750 $HOME/.docker/cli-plugins/docker-buildx
  #- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
install:
  # Install QEMU
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --name xbuilder
  # Chech Version
  - lsb_release -a
  - uname -r
  - docker version
  - docker buildx version
  - ls -al /proc/sys/fs/binfmt_misc/
  - docker buildx inspect xbuilder --bootstrap
  - docker buildx ls
script: 
  - travis_wait 30 sh -c 'bash ci.sh'
