language: bash
#services:
#  - docker
dist: focal
sudo: required
env:
  global:
    - DOCKER_REPO=kevin0205/metricbeat
    - TARGET_ARCH=linux/amd64,linux/64
    - TARGET_VERSION=7.5.2 
    - IMAGE_TAG=kevin0205/metricbeat 
    - SPECIFIC_TAG="-t '$IMAGE_TAG:$TARGET_VERSION'"
before_install:
  - curl -fsSL https://get.docker.com | sh
  - sudo systemctl restart docker
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - mkdir -p $HOME/.docker/cli-plugins
  - wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
  - chmod 0750 $HOME/.docker/cli-plugins/docker-buildx
  #- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  #- docker version
  #- docker buildx version
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  #- ls -al /proc/sys/fs/binfmt_misc/
  - docker buildx create --use --name xbuilder
  #- docker buildx inspect xbuilder --bootstrap
  #- docker buildx ls
#script: 
#  - travis_wait 50 sh -c 'bash ci.sh'

script: docker buildx build --platform "$TARGET_ARCH" --build-arg VERSION="$TARGET_VERSION" -t "$IMAGE_TAG" "$SPECIFIC_TAG" . --push
