name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Checkout GitHub Action Master'
        uses: actions/checkout@v2
      -
        name: Dockerhub login
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      -
        name: Install Docker Buildx
        if: success()
        mkdir -p $HOME/.docker/cli-plugins
        wget -O $HOME/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
        chmod 0750 $HOME/.docker/cli-plugins/docker-buildx
      -
        name: Install QEMU
        curl -fsSL https://get.docker.com | sh
        sudo systemctl restart docker
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --name xbuilder
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform=linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --file ./Dockerfile .
